import type { Metadata } from "next";
import {Comfortaa} from "next/font/google";
import "./globals.css";
import { ClerkProvider} from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";



const font1 = Comfortaa({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
<ClerkProvider>
<html lang="en">
  <body className={font1.className}>
    <Toaster/>
    <ExitModal/>
    <HeartsModal/>
    <PracticeModal/>
    {children}
  </body>
</html>
</ClerkProvider>
  );
}
